/**
 * Lucide → Phosphor shim.
 *
 * Re-exports Phosphor (thin) icon components under the lucide-react names
 * already used across the codebase. This lets us swap visual style globally
 * without touching ~95 component files. Sizing via Tailwind classes
 * (w-4 h-4, etc.) keeps working because Phosphor SVGs honour CSS width/height.
 *
 * Global thin weight is applied via <IconContext.Provider> in main.tsx.
 */
export {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Aperture,
  ArrowDownRight,
  ArrowsDownUp as ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ChartBar as BarChart3,
  BookBookmark as BookMarked,
  BookOpen,
  Book as BookX,
  Robot as Bot,
  Brain,
  Buildings as Building2,
  Calculator,
  Calendar,
  Check,
  CheckCircle as CheckCircle2,
  CheckSquare,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Circle,
  Record as CircleDot,
  Clock,
  Code,
  Copy,
  Cpu,
  Database,
  Download,
  Eraser,
  Eye,
  EyeSlash as EyeOff,
  File,
  FileMagnifyingGlass as FileSearch,
  FileText,
  Flag,
  Fire as Flame,
  Flask as FlaskConical,
  Gauge,
  GitBranch,
  GitCommit,
  GitDiff as GitCompare,
  GraduationCap,
  GridFour as Grid3X3,
  Question as HelpCircle,
  Highlighter,
  Image,
  Key as KeyRound,
  Keyboard,
  Translate as Languages,
  Stack as Layers,
  SquaresFour as Layout,
  SquaresFour as LayoutDashboard,
  GridFour as LayoutGrid,
  Layout as LayoutTemplate,
  Books as Library,
  Lightbulb,
  ChartLine as LineChart,
  LinkSimple as Link2,
  List,
  TreeStructure as ListTree,
  CircleNotch as Loader2,
  Lock,
  MapTrifold as Map,
  MapPin,
  ArrowsOut as Maximize2,
  ChatCircle as MessageCircle,
  Chat as MessageSquare,
  Microphone as Mic,
  MicrophoneSlash as MicOff,
  ArrowsIn as Minimize2,
  Minus,
  Moon,
  Network,
  Palette,
  SidebarSimple as PanelLeftClose,
  Sidebar as PanelLeftOpen,
  Pause,
  Pen,
  PencilLine as PenLine,
  PencilSimpleLine as PenSquare,
  PenNib as PenTool,
  Pencil,
  PushPin as Pin,
  Play,
  Plus,
  PresentationChart as Presentation,
  Printer,
  ArrowClockwise as Redo2,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  Ruler,
  FloppyDisk as Save,
  Scales as Scale,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Sliders as Settings2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smiley as Smile,
  Sparkle as Sparkles,
  Square,
  Star,
  Note as StickyNote,
  Sun,
  Table as Table2,
  Tag,
  Target,
  Terminal,
  Timer,
  Trash as Trash2,
  TrendUp as TrendingUp,
  TextT as Type,
  ArrowCounterClockwise as Undo2,
  LockOpen as Unlock,
  UploadSimple as Upload,
  Users,
  SpeakerHigh as Volume2,
  MagicWand as Wand2,
  X,
  XCircle,
  Lightning as Zap,
} from '@phosphor-icons/react';

export type { Icon as LucideIcon } from '@phosphor-icons/react';
